version: '3.8'

services:
  mysql:
    image: mysql
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: EwYNY0Dvz6bst3vI
      MYSQL_DATABASE: TiendaPC
      MYSQL_USER: alexander
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /home/alexander/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:



